# Generated by Django 5.2.6 on 2026-02-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_alter_pokemon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(null=True, upload_to='image/bulbazavr.png', verbose_name='Ваше изображение'),
        ),
        migrations.CreateModel(
            name='PokemonEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entites', to='pokemon_entities.pokemon', verbose_name='Ссылка на покемона')),
            ],
        ),
    ]
