# Generated by Django 5.2.6 on 2026-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemon_image_pokemonentities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentities',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта покемона'),
        ),
        migrations.AddField(
            model_name='pokemonentities',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота покемона'),
        ),
    ]
