# Generated by Django 5.2.6 on 2026-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentities_lat_pokemonentities_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentities',
            name='appeared_at',
            field=models.DateTimeField(null=True, verbose_name='Дата появления'),
        ),
        migrations.AddField(
            model_name='pokemonentities',
            name='disappeared_at',
            field=models.DateTimeField(null=True, verbose_name='Дата исчезновения'),
        ),
    ]
