# Generated by Django 5.2.6 on 2026-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentities_appeared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentities',
            name='ataka',
            field=models.IntegerField(null=True, verbose_name='Атака покемона'),
        ),
        migrations.AddField(
            model_name='pokemonentities',
            name='health',
            field=models.IntegerField(null=True, verbose_name='Здоровье покемона'),
        ),
        migrations.AddField(
            model_name='pokemonentities',
            name='level',
            field=models.IntegerField(null=True, verbose_name='Уровень покемона'),
        ),
        migrations.AddField(
            model_name='pokemonentities',
            name='vinoclivost',
            field=models.IntegerField(null=True, verbose_name='Выносливость покемона'),
        ),
        migrations.AddField(
            model_name='pokemonentities',
            name='zashita',
            field=models.IntegerField(null=True, verbose_name='Защита покемона'),
        ),
    ]
