# Generated by Django 5.2.6 on 2026-02-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemonentities_ataka_pokemonentities_health_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentities',
            old_name='ataka',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='pokemonentities',
            old_name='zashita',
            new_name='protection',
        ),
        migrations.RenameField(
            model_name='pokemonentities',
            old_name='vinoclivost',
            new_name='stamina',
        ),
    ]
