# Generated by Django 5.2.6 on 2026-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_rename_ataka_pokemonentities_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/bulbazavr.png', verbose_name='Ваше изображение'),
        ),
    ]
