# Generated by Django 5.2.6 on 2026-02-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_alter_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Описание покемона'),
        ),
    ]
