# Generated by Django 5.2.6 on 2026-02-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_rename_title_pokemon_title_ru_pokemon_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_ru',
            new_name='title',
        ),
    ]
