# Generated by Django 5.2.6 on 2026-02-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_rename_title_ru_pokemon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='previos_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Предыдущая эволюция покемона'),
        ),
    ]
