# Generated by Django 5.2.6 on 2026-02-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_alter_pokemon_previos_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previos_evolution',
            new_name='previous_evolution',
        ),
    ]
