# Generated by Django 5.2.6 on 2026-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_alter_pokemon_description_alter_pokemon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentities',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentities',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота покемона'),
        ),
    ]
