# Generated by Django 5.2.6 on 2026-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_alter_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentities',
            name='appeared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentities',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исчезновения'),
        ),
    ]
